#!/bin/bash
logDebug 'Configuring output directory...'

requireVariable BO_Project      || return 1
createDirectory $BO_Project/out || return 1

# Return, but do NOT exit, with a success code
return 1

