#!/bin/bash
echo "TRACE: Executing '$BASH_SOURCE'"

export PIP_REQUIRE_VIRTUALENV=true
export PIP_RESPECT_VIRTUALENV=true

requireVariable PIP_DOWNLOAD_CACHE  || return 1
createDirectory $PIP_DOWNLOAD_CACHE || return 1

# Return, but do NOT exit, with a success code
return 1

