#!/bin/bash
# Activate this project

echo 'WARN:  Should be executed as: "source activate", was it?'

# Remember the current directory as our project home
export HomeProject=${PWD}

source $HomeProject/project.env
source $HomeProject/configure_build_tools
source $HomeProject/bin_shared/helper/configure_project
