#!/bin/bash
echo "TRACE: Executing '$BASH_SOURCE'"
logDebug 'Running Nose-based tests on this project...'

requireVariable BO_Project
requireVariable BO_HomePackage

cd "${BO_Project}/src"
abortOnFail "$?"

_Cmd=nosetests
_Cmd="$_Cmd --config=${BO_Project}/cfg/nose.cfg"
_Cmd="$_Cmd --id-file=${BO_Project}/.noseids"
_Cmd="$_Cmd --cover-package=${BO_HomePackage}"
$_Cmd
abortOnFail "$?"

