#!/bin/bash
echo "TRACE: Executing '$BASH_SOURCE'"
logDebug 'Running pylint on this project...'

requireVariable BO_Package
requireVariable BO_Project

cd "${BO_Project}/src"

_Cmd=pylint
_Cmd="$_Cmd --rcfile=${BO_Project}/cfg/pylintrc"
_Cmd="$_Cmd ${BO_Package}"
$_Cmd | tee ${BO_Project}/out/pylint.out

