import script_bash
import script_briteonyx

from throw_out_your_templates_3_core_visitor_map import VisitorMap


class Script(script_briteonyx.Script):
    def __init__(self):
        script_briteonyx.Script.__init__(self)

    def abort_if_activated(self):
        self.line()
        self.rule()
        self.note('ABORT: if project is already activated')
        self.text('[[ -n "$BO_Project" ]]').and_()
        self.echo('''"FATAL: Project '$BO_Project' is already activated, aborting"''').and_()
        self.exit(100)
        self.end_line()

    def activate_for_linux(self):
        self.line()
        self.rule()
        self.comment('Activate as a Linux project')
        self.line()
        self.assign('Script', '"$BO_Home/helper/activation/activate.src"').end_line()
        self.require_script('"$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.source('         "$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()

    def comments(self):
        self.note("We MUST NOT EVER 'exit' during BriteOnyx bootstrap or activation")
        self.rule()
        self.add_debugging_comment()
        self.someday('Add inverse commands to isolate debugging')
        self.line()
        self.rule()
        self.comment('Activate the BriteOnyx framework to manage this project directory tree')
        self.comment()
        self.note("This script, and EVERY script that it calls, must NOT invoke 'exit'!  The user calling this")
        self.comment('  script must be allowed to preserve their shell and every effort must be made to inform the user')
        self.comment('  of problems while continuing execution where possible.  Terminating the shell robs the user of')
        self.comment("  useful feedback and interrupts their work, which is unacceptable.  Instead, the BASH 'return'")
        self.comment('  statement should be invoked to end execution with an appropriate status code.')
        self.comment()
        self.someday('Verify that $BO_Project does indeed point to the root of our project directory tree')

    def capture_incoming_environment(self):
        self.line()
        self.comment('Capture incoming BASH environment')
        self.if_('[[ -n "$TMPDIR" ]]').seq().then().end_line()
        self.text('  ').line('env | sort >$TMPDIR/BO-env-incoming.out')
        self.elif_('[[ -n "$BO_Project" ]]').seq().then().end_line()
        self.text('  ').line('env | sort >$BO_Project/BO-env-incoming.out')
        self.else_().end_line()
        self.text('  ').line('env | sort >$PWD/BO-env-incoming.out')
        self.fi().end_line()

    def capture_outgoing_environment(self):
        self.line()
        self.comment('Capture outgoing BASH environment')
        self.if_('[[ -n "$TMPDIR" ]]').seq().then().end_line()
        self.text('  ').line('env | sort >$TMPDIR/BO-env-outgoing.out')
        self.elif_('[[ -n "$BO_Project" ]]').seq().then().end_line()
        self.text('  ').line('env | sort >$BO_Project/BO-env-outgoing.out')
        self.else_().end_line()
        self.text('  ').line('env | sort >$PWD/BO-env-outgoing.out')
        self.fi().end_line()

    def configure_for_briteonyx(self):
        self.line()
        self.rule()
        self.comment('Configure for BriteOnyx')
        self.line()
        self.assign('Script', '"$BO_Project/BriteOnyx/env.src"').end_line()
        self.require_script('"$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.source('         "$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()

    def configure_for_project(self):
        self.line()
        self.rule()
        self.comment('Configure for this project')
        self.line()
        self.assign('Script', '$BO_Project/env.src').end_line()
        self.require_script('$Script').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.source('         $Script').or_()
        self.failed().or_()
        self.return_('$?').end_line()

    def configure_for_user(self):
        self.line()
        self.rule()
        self.comment('Configure for this user')
        self.line()
        self.assign('Script', '$HOME/.BriteOnyx.src').end_line()
        self.require_script('"$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.source('         "$Script"').or_()
        self.failed().or_()
        self.return_('$?').end_line()

    def copy_starter_files(self):
        self.line()
        self.rule()
        self.comment('Copy starter files into place as necessary')
        self.line()
        self.assign('DirSrc', '$BO_Project/BriteOnyx/starter').end_line()
        self.line()
        self.require_variable('HOME').end_line()
        self.assign('DirTgt', '$HOME').end_line()
        self.text('[[ ! -e "$DirTgt" ]]').and_()
        self.line('mkdir -p $DirTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/.BriteOnyx.src').end_line()
        self.comment('Move previous scripts to new path')
        self.text('[[   -f $DirTgt/BriteOnyx.src      ]]').and_()
        self.line('mv $DirTgt/BriteOnyx.src      $FileTgt')
        self.text('[[   -f $DirTgt/BriteOnyx-env.bash ]]').and_()
        self.line('mv $DirTgt/BriteOnyx-env.bash $FileTgt')
        self.text('[[   -f $DirTgt/BriteOnyx-env.src  ]]').and_()
        self.line('mv $DirTgt/BriteOnyx-env.src  $FileTgt')
        self.comment('Copy starter script, if necessary')
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/user-BriteOnyx.src $FileTgt')
        self.line()
        self.assign('DirTgt', '$BO_Project').end_line()
        self.text('[[ ! -e "$DirTgt" ]]').and_()
        self.line('mkdir -p $DirTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/env.src').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-env.src $FileTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/.hgignore').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project.hgignore $FileTgt')
        self.line()
        self.assign('DirTgt', '$BO_Project/bin').end_line()
        self.text('[[ ! -e "$DirTgt" ]]').and_()
        self.line('mkdir -p $DirTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/project-fix-permissions.bash').end_line()
        self.comment('Move previous scripts to new path')
        self.text('[[   -f $DirTgt/all-fix-permissions.bash ]]').and_()
        self.line('mv $DirTgt/all-fix-permissions.bash $FileTgt')
        self.comment('Copy starter script, if necessary')
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-fix-permissions.bash $FileTgt')
        self.line()
        self.line(": <<'DisabledContent'")
        self.assign('FileTgt', '$DirTgt/declare.src').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-declare.src $FileTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/development.rst').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-development.rst $FileTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/README.rst').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-README.rst $FileTgt')
        self.line()
        self.assign('DirTgt', '$BO_Project/bin/helper/Linux').end_line()
        self.text('[[ ! -e $DirTgt ]]').and_()
        self.line('mkdir -p $DirTgt')
        self.line()
        self.assign('FileTgt', '$DirTgt/declare-BASH.src').end_line()
        self.text('[[ ! -f $FileTgt ]]').and_()
        self.line('cp $DirSrc/project-declare-BASH.src $FileTgt')
        self.line('DisabledContent')

    def create_random_tmpdir(self):
        self.line()
        self.comment('Create random TMPDIR')
        self.assign('Dir', '$(mktemp --tmpdir -d BO-XXXXXXXX)').end_line()
        self.text('[[ -d "$Dir" ]]').and_()
        self.export('TMPDIR', '$Dir').end_line()

    def declare_for_bootstrap(self):
        self.line()
        self.rule()
        self.comment('Declare BriteOnyx support functionality')
        self.line()
        self.assign('Script', '"$BO_Project/BriteOnyx/declare.src"').end_line()
        self.text('[[ ! -f "$Script" ]]').and_()
        self.echo_fatal("Missing script '$Script'").and_()
        self.return_(63).end_line()
        self.source('"$Script"').seq()
        self.assign('Status', '$?').end_line()
        self.text('[[ "${Status}" -ne 0 ]]').and_()
        self.echo_fatal("Script exited with '${Status}'").and_()
        self.return_('${Status}').end_line()
        self.line()
        self.rule()
        self.note('Now that we have our support functionality declared, we can use it from here on')

    def declare_for_project(self):
        self.line()
        self.rule()
        self.comment('Declare optional project functionality')
        self.line()
        self.assign('Script', '"$BO_Project/declare.src"').end_line()
        self.if_('[[ -f "$Script" ]]').seq().then().end_line()
        self.text('  ').source('"$Script"').seq()
        self.assign('Status', '$?').end_line()
        self.text('  ').text('[[ "${Status}" -ne 0 ]]').and_()
        self.echo_fatal("Script exited with '${Status}'").and_()
        self.return_('${Status}').end_line()
        self.fi().end_line()

    def demonstrate_logging(self):
        self.line()
        self.rule()
        self.comment('Demonstrate logging')
        self.line()
        self.line('logDebug  "EXAMPLE: This is a debugging message"')
        self.line('logInfo   "EXAMPLE: This is an informational message"')
        self.line('logWarn   "EXAMPLE: This is a warning message"')
        self.line('logError  "EXAMPLE: This is an error message"')
        self.line('_logFatal "EXAMPLE: This is a fatal message"')

    def generate(self):
        self.add_source_header()
        self.comments()
        self.abort_if_activated()
        self.create_random_tmpdir()
        self.initialize_logging_file()
        self.capture_incoming_environment()
        self.remember_project_root()
        self.declare_for_bootstrap()
        self.normalize_reference_to_project_root()
        self.copy_starter_files()
        self.configure_for_user()
        self.configure_for_project()
        self.configure_for_briteonyx()
        self.verify_briteonyx_bootstrap()
        self.remember_path()
        self.activate_for_linux()
        self.set_tmpdir()
        self.declare_for_project()
        self.demonstrate_logging()
        self.shutdown()
        self.add_disabled_content_footer()

    def initialize_logging_file(self):
        self.line()
        self.comment('Initialize BriteOnyx logging file')
        self.assign('BO_FileLog', 'BO.log').end_line()
        self.if_('[[ -n "$TMPDIR" ]]').seq().then().end_line()
        self.text('  ').export('BO_FileLog', '$TMPDIR/$BO_FileLog').end_line()
        self.elif_('[[ -n "$BO_Project" ]]').seq().then().end_line()
        self.text('  ').export('BO_FileLog', '$BO_Project/$BO_FileLog').end_line()
        self.else_().end_line()
        self.text('  ').export('BO_FileLog', '$PWD/$BO_FileLog').end_line()
        self.fi().end_line()
        self.echo_info("Activating...").text(' >$BO_FileLog').end_line()
        self.echo_info("Activating the BriteOnyx framework for this project...").end_line()
        self.echo_warn("This script MUST be executed as 'source activate.src', WAS IT?").end_line()

    def normalize_reference_to_project_root(self):
        self.line()
        self.require_variable("'BO_Project'").or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.trace_variable("'BO_Project'").end_line()
        self.export('BO_Project', '"$(boNodeCanonical $BO_Project)"').end_line()
        self.trace_variable("'BO_Project'").end_line()
        self.bo_log_info("Canonical form of BO_Project directory pathname is '$BO_Project'")
        self.end_line()
        self.require_directory('"$BO_Project"').or_()
        self.failed().or_()
        self.return_('$?').end_line()

    def remember_path(self):
        self.line()
        self.rule()
        self.comment('Remember PATH')
        self.line()
        self.text('[[ -z "$BO_PathSystem" ]]').and_().continue_()
        self.text('  ').export('BO_PathSystem', '$PATH').and_().continue_()
        self.text('  ').echo_info("Remembering BO_PathSystem='$BO_PathSystem'").end_line()

    def remember_project_root(self):
        self.line()
        self.rule()
        self.comment('Remember the directory containing this script as our project root')
        self.line()
        self.export('BO_Project', '"$(dirname $BASH_SOURCE)"').end_line()
        self.line()
        self.todo('REVIEW: Shall we NOT cd into our project directory since it changes')
        self.comment("the caller's execution environment?")
        self.comment('cd "$BO_Project" || return $?')

    def set_tmpdir(self):
        self.line()
        self.rule()
        self.comment('Set TMPDIR ')
        self.comment('DISABLED: MOVED: to Linux activation script')
        self.line()
        self.comment('export TMPDIR=$TMPDIR/$BO_ProjectName')
        self.comment('''echo "INFO:  Remembering TMPDIR='$TMPDIR'"''')

    def shutdown(self):
        self.line()
        self.rule()
        self.comment('Shutdown')
        self.line()
        self.log_info("Project '$BO_ProjectName' in directory '$BO_Project' is now activated, done.")
        self.end_line()
        self.capture_outgoing_environment()

    def verify_briteonyx_bootstrap(self):
        self.line()
        self.rule()
        self.comment('Verify BriteOnyx bootstrap configuration')
        self.line()
        self.require_variable('  BO_Home').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.require_directory('$BO_Home').or_()
        self.failed().or_()
        self.return_('$?').end_line()
        self.line()
        self.require_variable('BO_ProjectName').or_()
        self.failed().or_()
        self.return_('$?').end_line()


VISITOR_MAP = VisitorMap(parent_map=script_briteonyx.VISITOR_MAP)


def build():
    script = Script()
    script.generate()
    return script
    
def render(target_directory, target_file):
    script_bash.render(build(), VISITOR_MAP, target_directory, target_file)


""" Disabled content
"""

