#!/bin/bash

echo 'INFO:  Configure output directory'

[[   -z "$HomeProject" ]] && \
  echo 'FATAL:  Missing value for $HomeProject' && exit 1
[[ ! -e "$HomeProject/out" ]] && \
  echo "INFO:  Creating $HomeProject/out" && \
  mkdir "$HomeProject/out"
[[   -d "$HomeProject/out" ]] && \
  echo "INFO:  Directory $HomeProject/out exists"
