#!/bin/bash

echo 'INFO:  Configure temporary directory (TMPDIR)'

[[   -z "$TMPDIR" ]] && echo 'FATAL: Missing value for $TMPDIR' && exit 1
[[ ! -e "$TMPDIR" ]] && echo "INFO:  Creating $TMPDIR" && mkdir -p "$TMPDIR"
[[ ! -d "$TMPDIR" ]] && echo "FATAL: Missing directory $TMPDIR" && exit 1

