#!/bin/bash

echo 'INFO:  Configure system execution PATH'

_PathBuild=$HomeBuildTools/bin_shared
_PathProject=$HomeProject/bin
_PathPve=$HomeProject/PVE/bin
_PathSystem=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH=${_PathProject}:${_PathBuild}:${_PathPve}:${_PathSystem}
